all: build

build:
	pdflatex rapport_tp1.tex
	pdflatex rapport_tp1.tex
	pdflatex rapport_tp2.tex
	pdflatex rapport_tp2.tex
	pdflatex rapport_tp3.tex
	pdflatex rapport_tp3.tex
	pdflatex rapport_tp4.tex
	pdflatex rapport_tp4.tex

clean:
	rm *.{aux,log,toc,out}